services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rootpassword
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=n8nuser
      - POSTGRES_NON_ROOT_PASSWORD=n8npassword
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./scripts/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: rabbitmq-broker
    environment:
      - RABBITMQ_DEFAULT_USER=n8nuser
      - RABBITMQ_DEFAULT_PASS=n8npassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-rabbitmq_stream advertised_host localhost'
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-main
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=test12345
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_LOG_LEVEL=debug
      - GENERIC_TIMEZONE=Atlantic/Canary
      - TZ=Atlantic/Canary
      - DB_TYPE=postgresdb
      - N8N_METRICS=true
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8nuser
      - DB_POSTGRESDB_PASSWORD=n8npassword
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    # etc.

  task-runners:
    image: n8nio/runners:custom # Built from the Dockerfile in deploy/n8n/n8niorunners
    container_name: n8n-runners
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-main:5679
      - N8N_RUNNERS_AUTH_TOKEN=test12345
      # etc.
    depends_on:
      - n8n

volumes:
  n8n_data: {}
  db_storage: {}